In [1]:
# cross validation 

from sklearn.linear_model import  LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import pandas as pd

digits =  load_digits()


In [2]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [3]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(digits.data , digits.target , test_size = 0.3)

In [4]:
lr =  LogisticRegression()

In [6]:
lr.fit(x_train , y_train )
lr.score(x_test , y_test)

C:\Users\sonus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9592592592592593

In [7]:
svm = SVC()
svm.fit(x_train , y_train )
svm.score(x_test , y_test)

0.9833333333333333

In [8]:
rf = RandomForestClassifier()

In [9]:
rf.fit(x_train , y_train )
rf.score(x_test , y_test)

0.9740740740740741

In [10]:
from sklearn.model_selection import KFold

In [11]:
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [12]:
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index , test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [13]:
def get_score(model , x_train , x_test , y_train , y_test):
    model.fit(x_train , y_train)
    return model.score(x_test , y_test)

In [14]:
get_score(SVC(), x_train , x_test , y_train, y_test)

0.9833333333333333

In [15]:
from sklearn.model_selection import StratifiedKFold

In [16]:
folds = StratifiedKFold(n_splits = 3) 

In [22]:
scores_l = []
scores_svm = []
scores_rf = []
for train_index , test_index in kf.split(digits.data):
    x_train , x_test , y_train , y_test = digits.data[train_index] ,\
    digits.data[test_index], digits.target[train_index] , digits.target[test_index]
    scores_l.append(get_score(LogisticRegression() ,x_train , x_test , y_train , y_test ))
    scores_svm.append(get_score(RandomForestClassifier() ,x_train , x_test , y_train , y_test ))
    scores_rf.append(get_score(SVC() ,x_train , x_test , y_train , y_test ))
            

C:\Users\sonus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\sonus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

In [23]:
scores_svm

[0.9348914858096828, 0.9649415692821369, 0.9265442404006677]

In [24]:
scores_rf

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [25]:
from sklearn.model_selection import cross_val_score


In [26]:
cross_val_score(LogisticRegression() , digits.data , digits.target)

C:\Users\sonus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\sonus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [27]:
cross_val_score(SVC() , digits.data , digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [28]:
cross_val_score(RandomForestClassifier() , digits.data , digits.target)

array([0.93888889, 0.91111111, 0.95543175, 0.9637883 , 0.9275766 ])

In [29]:
cross_val_score(RandomForestClassifier(n_estimators=15) , digits.data , digits.target)

array([0.91388889, 0.88333333, 0.91922006, 0.93871866, 0.91086351])