In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('dummy variables.csv')

In [3]:
df

,area,price,Houses
0,2600,550000,monrea township
1,3000,565000,monrea township
2,3200,610000,monrea township
3,3600,680000,monrea township
4,4000,725000,monrea township
5,2600,585000,west windsor
6,2800,615000,west windsor
7,3300,650000,west windsor
8,3600,710000,west windsor
9,2600,575000,robbinsville


In [4]:
df.Houses.isnull()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
Name: Houses, dtype: bool

In [5]:
dummies = pd.get_dummies(df.Houses )

In [8]:
dummies

,monrea township,robbinsville,west windsor
0,True,False,False
1,True,False,False
2,True,False,False
3,True,False,False
4,True,False,False
5,False,False,True
6,False,False,True
7,False,False,True
8,False,False,True
9,False,True,False


In [9]:
merged = pd.concat([df, dummies],axis ='columns')
merged

,area,price,Houses,monrea township,robbinsville,west windsor
0,2600,550000,monrea township,True,False,False
1,3000,565000,monrea township,True,False,False
2,3200,610000,monrea township,True,False,False
3,3600,680000,monrea township,True,False,False
4,4000,725000,monrea township,True,False,False
5,2600,585000,west windsor,False,False,True
6,2800,615000,west windsor,False,False,True
7,3300,650000,west windsor,False,False,True
8,3600,710000,west windsor,False,False,True
9,2600,575000,robbinsville,False,True,False


In [10]:
last = merged.drop(['Houses','west windsor'], axis = 'columns')
last

,area,price,monrea township,robbinsville
0,2600,550000,True,False
1,3000,565000,True,False
2,3200,610000,True,False
3,3600,680000,True,False
4,4000,725000,True,False
5,2600,585000,False,False
6,2800,615000,False,False
7,3300,650000,False,False
8,3600,710000,False,False
9,2600,575000,False,True


In [11]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [12]:
x = last.drop('price', axis = 'columns')
x

,area,monrea township,robbinsville
0,2600,True,False
1,3000,True,False
2,3200,True,False
3,3600,True,False
4,4000,True,False
5,2600,False,False
6,2800,False,False
7,3300,False,False
8,3600,False,False
9,2600,False,True


In [13]:
y = last.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [14]:
model.fit(x,y)

LinearRegression()

In [15]:
model.predict([[2800,0 , 1]])

C:\Users\sonus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590775.63964739])

In [16]:
model.predict([[3400,0 , 0]])

C:\Users\sonus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([681241.66845839])

In [17]:
model.score(x, y)

0.9573929037221872

In [18]:
df

,area,price,Houses
0,2600,550000,monrea township
1,3000,565000,monrea township
2,3200,610000,monrea township
3,3600,680000,monrea township
4,4000,725000,monrea township
5,2600,585000,west windsor
6,2800,615000,west windsor
7,3300,650000,west windsor
8,3600,710000,west windsor
9,2600,575000,robbinsville


In [19]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [20]:
dfle = df

In [21]:
dfle.Houses = le.fit_transform(dfle.Houses)
dfle

,area,price,Houses
0,2600,550000,0
1,3000,565000,0
2,3200,610000,0
3,3600,680000,0
4,4000,725000,0
5,2600,585000,2
6,2800,615000,2
7,3300,650000,2
8,3600,710000,2
9,2600,575000,1


In [22]:
x = df[['Houses', 'area']].values
x

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [23]:
y = dfle.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [34]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()  # OneHotEncoder(categorical_features=[0])

In [35]:
OneHotEncoder.__init__(ohe)

In [36]:
x = ohe.fit_transform(x).toarray()

In [37]:
x = x[:,1:]

In [38]:
model.fit(x,y)


LinearRegression()

In [39]:
model.predict([[1,0, 2800]])

ValueError: X has 3 features, but LinearRegression is expecting 21 features as input.